accelerator: null
accumulate_grad_batches: null
adl_reg: 1.0
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 32
benchmark: false
beta1: 0.9
beta2: 0.999
check_val_every_n_epoch: 1
checkpoint_callback: null
checkpoint_path: null
data_dir: ../../data
dec_latent_size:
- 512
- 256
- 512
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
enc_combined_latent_size:
- 256
enc_combined_output_size: 128
enc_command_latent_size:
- 256
- 128
enc_command_output_size: 128
enc_dest_latent_size:
- 8
- 16
enc_latent_size:
- 128
- 50
enc_layout_interm_size: 512
enc_layout_latent_size:
- 256
- 128
enc_layout_output_size: 128
encoder: ResNet-18
fast_dev_run: false
fdim: 16
flush_logs_every_n_steps: null
gpus: 0,
gradient_clip_algorithm: null
gradient_clip_val: null
height: 200
input_type: layout
ipus: null
kld_reg: 0.001
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 0.0001
max_epochs: 50
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
momentum: 0.9
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
neighbor_dist_thresh: 0.1
non_local_dim: 128
non_local_g_size:
- 256
- 128
- 64
non_local_phi_size:
- 256
- 128
- 64
non_local_pools: 3
non_local_theta_size:
- 256
- 128
- 64
num_nodes: 1
num_path_nodes: 20
num_processes: 1
num_sanity_val_steps: 2
num_workers: 4
overfit_batches: 0.0
patience: 10
pecnet_config: null
plugins: null
precision: 32
predictor_latent_size:
- 1024
- 512
- 256
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
save_dir: PECNet
seed: 42
sigma: 0.13
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
terminate_on_nan: null
test: false
threshold: 1
tpu_cores: null
track_grad_norm: -1
unrolled: true
use_ref_obj: true
val_check_interval: 1.0
weight_decay: 0.0
weights_save_path: null
weights_summary: top
width: 300
zdim: 16
