neighbor_dist_thresh: 0.1
enc_layout_output_size: 512
enc_layout_latent_size:
- 512
- 256
enc_command_latent_size:
- 512
- 256
enc_dest_latent_size:
- 8
- 16
enc_latent_size:
- 8
- 50
non_local_theta_size:
- 256
- 128
- 64
non_local_phi_size:
- 256
- 128
- 64
non_local_g_size:
- 256
- 128
- 64
dec_latent_size:
- 1024
- 512
- 1024
predictor_latent_size:
- 1024
- 512
- 256
non_local_dim: 128
fdim: 16
zdim: 16
sigma: 0.065
kld_reg: 0.01
adl_reg: 0.0
mu: 0
non_local_pools: 3
